=== HichamGuessab/XMLManipulationLab/TP1/Exercice 6-1/annuaireV1.dtd
<!ELEMENT annuaire (personne*, societe*)>

<!ELEMENT personne (nom, prenom, email?, telephone_personnel+, activite)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT telephone_personnel (#PCDATA)>
<!ELEMENT activite (#PCDATA)>

<!ELEMENT societe (nom_societe, branche+, info_directeur, avis?)>
<!ELEMENT nom_societe (#PCDATA)>
<!ELEMENT branche (adresse, telephone_branche, jours_fermeture, annee_ouverture)>
<!ELEMENT adresse (#PCDATA)>
<!ELEMENT telephone_branche (#PCDATA)>
<!ELEMENT jours_fermeture (#PCDATA)>
<!ELEMENT annee_ouverture (#PCDATA)>
<!ELEMENT info_directeur (nom, email)>
<!ELEMENT avis (#PCDATA)>

<!-- On pourrait aussi factoriser comme étant des éléments globaux
        nom/nom_societe en un seul élément 'nom'
            et
        telephone_personnel/telephone_branche en un seul élément 'telephone'
        mais j'ai préféré avoir des éléments distincts afin d'en faciliter la récupération
-->

=== HichamGuessab/XMLManipulationLab/TP1/Exercice 6-1/annuaireV1.xml
<?xml version="1.0"?>
<!DOCTYPE annuaire SYSTEM "annuaireV1.dtd">
<annuaire>
    <personne>
        <nom>Guessab</nom>
        <prenom>Hicham</prenom>
        <email>hicham.guessab@example.com</email>
        <telephone_personnel>0123456789</telephone_personnel>
        <telephone_personnel>0123456798</telephone_personnel>
        <activite>DÃ©veloppeur</activite>
    </personne>
    <societe>
        <nom_societe>Inovich</nom_societe>
        <branche>
            <adresse>123 rue de Paris</adresse>
            <telephone_branche>0123456789</telephone_branche>
            <jours_fermeture>Dimanche</jours_fermeture>
            <annee_ouverture>2024</annee_ouverture>
        </branche>
        <info_directeur>
            <nom>Marie Curie</nom>
            <email>marie.curie@techcorp.com</email>
        </info_directeur>
        <avis>Superbe entreprise wouaw.</avis>
    </societe>
</annuaire>
