=== HichamGuessab/XMLManipulationLab/TP1/Exercice 6-1/annuaireV2.dtd
<!ELEMENT annuaire (personne*, societe*)>

<!ELEMENT personne (nom, prenom, email?, telephone_personnel+, activite)>
<!ELEMENT nom (#PCDATA)>
    <!ATTLIST nom nom_de_naissance CDATA #IMPLIED>
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT telephone_personnel (#PCDATA)>
<!ELEMENT activite (#PCDATA)>

<!ELEMENT societe (nom_societe, branche+, info_directeur, avis?)>
<!ELEMENT nom_societe (#PCDATA)>
<!ELEMENT branche (adresse, telephone_branche)>
    <!ATTLIST branche jours_fermeture CDATA "Dimanche">
    <!ATTLIST branche annee_d_ouverture (2024 | 2023 | 2022 | avant_2022 | inconnue) "inconnue">
<!ELEMENT jours_fermeture (#PCDATA)>
<!ELEMENT adresse (#PCDATA)>
<!ELEMENT telephone_branche (#PCDATA)>
<!ELEMENT info_directeur EMPTY>
    <!ATTLIST info_directeur
            nom CDATA #REQUIRED
            email CDATA #IMPLIED>
<!ELEMENT avis (#PCDATA)>

=== HichamGuessab/XMLManipulationLab/TP1/Exercice 6-1/annuaireV2.xml
<?xml version="1.0"?>
<!DOCTYPE annuaire SYSTEM "annuaireV2.dtd">
<annuaire>
    <personne>
        <nom nom_de_naissance="Guessab">Guessab</nom>
        <prenom>Hicham</prenom>
        <email>hicham.guessab@example.com</email>
        <telephone_personnel>0123456789</telephone_personnel>
        <activite>DÃ©veloppeur</activite>
    </personne>
    <societe>
        <nom_societe>Inovich</nom_societe>
        <branche
                jours_fermeture="Samedi"
                annee_d_ouverture="2023">
            <adresse>123 rue de Paris</adresse>
            <telephone_branche>0123456789</telephone_branche>
        </branche>
        <info_directeur nom="Marie Curie" email="marie.curie@techcorp.com"/>
        <avis>Excellente entreprise innovante.</avis>
    </societe>
</annuaire>
